### ISSUE TITLE
Cannot find module 'readable-stream'

### ISSUE THREAD

**Issue by r-cohen** [reid/node-jslint#103]
node -v: v0.10.25
npm -v: 1.4.28

Installed jslint via: npm install -g jslint
Calling jslint command provocs following error:

module.js:340
    throw err;
          ^
Error: Cannot find module 'readable-stream'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/.../.npm/jslint/0.6.6/package/lib/stream.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Thanks for any help on this.

**Comment by switheyw** [comment]
/usr/local/bin/node -v = 5.6.0
/usr/local/bin/npm -v = 3.10.5

I get the same errors as phearme was getting.  Is "the" npm directory ~/.npm or some other subdir?
I made the same updates to ~/.npm as noted above.  
 Instead of copying all of your lib files to /usr/local/lib I tried to install your node-jslint in /opt/local, copying jslint to /opt/local/bin, and all the files from your lib to /opt/local/lib.   Any suggestions?

**Comment by smikes** [comment]
Holy Necromancy, Switheyw!

I would recommend trying to install jslint as 

```
npm i -g jslint
```

You may want to try a node version manager.  (I use [nvm](https://github.com/creationix/nvm) on Linux and macOS, and I no longer run on Windows, so your choices may be different if you use a different platform mix.)  The nice thing about nvm is it automatically sets up a place for "globally installed" modules like jslint, and it sets it up so each version of node that's installed can have its own library of modules (if needed).
